#!/bin/tcsh

set num = $argv[1]

if ( $num == "" ) then
   echo "must specify draft number as first argument"
   exit 1
endif

# foreach i ( p1-messaging p2-semantics p4-conditional p5-range p6-cache p7-auth p8-cookies )

foreach i ( p1-messaging p2-semantics p4-conditional p5-range p6-cache p7-auth )
  cp -p $i.redxml draft-ietf-httpbis-$i-$num.xml
  cp -p $i.txt    draft-ietf-httpbis-$i-$num.txt
end
