#!/bin/tcsh

set num = $argv[1]

if ( $num == "" ) then
   echo "must specify draft number as first argument"
   exit 1
endif

if ( -d $num ) then
   echo "$num already exists"
   exit 2
endif

mkdir ../$num

foreach i ( p1-messaging p2-semantics p3-payload p4-conditional p5-range p6-cache p7-auth p8-cookies )
  cp -p $i.xml ../$num/draft-ietf-httpbis-$i-$num.xml
  cp -p $i.txt ../$num/draft-ietf-httpbis-$i-$num.txt
end
