<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               xmlns:x="http://purl.org/net/xml2rfc/ext"
               xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'
               version="1.0"
               exclude-result-prefixes="rdf x"
>

<xsl:output indent="yes" omit-xml-declaration="yes"/>

<xsl:output indent="yes" omit-xml-declaration="yes"/>

<xsl:template match="/">
  <xsl:variable name="table">
    <texttable align="left" suppress-title="true" anchor="iana.status.code.registration.table">
      <ttcol>Value</ttcol>
      <ttcol>Description</ttcol>
      <ttcol>Reference</ttcol>
      <xsl:apply-templates select="//section[iref/@item='Status Codes']">
        <xsl:sort select="iref[@item='Status Codes']/@subitem"/>
      </xsl:apply-templates>
    </texttable>
    <xsl:text>&#10;</xsl:text>
  </xsl:variable>

  <xsl:comment>AUTOGENERATED FROM extract-status-code-defs.xslt, do not edit manually</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <xsl:copy-of select="$table"/>
  <xsl:comment>(END)</xsl:comment>
  <xsl:text>&#10;</xsl:text>

  <!-- check against current version -->
  <xsl:variable name="oldtable" select="//texttable[@anchor='iana.status.code.registration.table']" />

  <xsl:if test="string($table//ttcol | $table//c) != string($oldtable//ttcol | $oldtable//c)">
    <xsl:message>WARNING: table contained inside source document needs to be updated!</xsl:message>
  </xsl:if>

</xsl:template>

<xsl:template match="section">
  <xsl:variable name="text" select="iref[@item='Status Codes']/@subitem"/>
  <xsl:text>&#10;</xsl:text>
  <c><xsl:value-of select="substring-before($text,' ')"/></c>
  <c><xsl:value-of select="substring($text,2+string-length(substring-before($text,' ')))"/></c>
  <c><xref target="{@anchor}"/></c>
</xsl:template>

</xsl:transform>