<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               xmlns:x="http://purl.org/net/xml2rfc/ext"
               version="1.0"
>

<xsl:output indent="yes" omit-xml-declaration="yes"/>

<xsl:template match="/">
  <xsl:comment>AUTOGENERATED FROM extract-status-code-defs.xslt, do not edit manually</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <xsl:comment>(START)</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <t>
    The HTTP Status Code Registry located at <eref target="http://www.iana.org/assignments/http-status-codes"/>
    should be updated with the registrations below:
  </t>
  <texttable>
    <ttcol>Value</ttcol>
    <ttcol>Description</ttcol>
    <ttcol>Reference</ttcol>
    <xsl:apply-templates select="//section[iref/@item='Status Codes']">
      <xsl:sort select="iref[@item='Status Codes']/@subitem"/>
    </xsl:apply-templates>
  </texttable>
  <t>
  </t>
  <xsl:text>&#10;</xsl:text>
  <xsl:comment>(END)</xsl:comment>
</xsl:template>

<xsl:template match="section">
  <xsl:variable name="text" select="iref[@item='Status Codes']/@subitem"/>
  <xsl:text>&#10;</xsl:text>
  <c><xsl:value-of select="substring-before($text,' ')"/></c>
  <c><xsl:value-of select="substring($text,2+string-length(substring-before($text,' ')))"/></c>
  <c><xref target="{@anchor}"/></c>
</xsl:template>

</xsl:transform>