<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               version="1.0"
>

<xsl:output indent="yes" omit-xml-declaration="yes" encoding="US-ASCII"/>

<xsl:template match="/">
  <xsl:comment>AUTOGENERATED FROM extract-header-defs.xslt, do not edit manually</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <xsl:comment>(START)</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <t>
    The Message Header Registry located at <eref target="http://www.iana.org/assignments/message-headers/message-header-index.html"/> should be updated
    with the permanent registrations below (see <xref target="RFC3864"/>):
  </t>
  <texttable>
    <ttcol>Header Field Name</ttcol>
    <ttcol>Protocol</ttcol>
    <ttcol>Status</ttcol>
    <ttcol>Reference</ttcol>
    <xsl:apply-templates select="//section[iref/@item='Headers']">
      <xsl:sort select="iref[@item='Headers']/@subitem"/>
    </xsl:apply-templates>
  </texttable>
  <t>
    The change controller is: "IETF (iesg@ietf.org) - Internet Engineering Task Force".
  </t>
  <xsl:text>&#10;</xsl:text>
  <xsl:comment>(END)</xsl:comment>
</xsl:template>

<xsl:template match="section">
  <xsl:text>&#10;</xsl:text>
  <c><xsl:value-of select="iref[@item='Headers']/@subitem"/></c>
  <c>http</c>
  <c>
    <xsl:choose>
      <xsl:when test="ancestor::middle">standard</xsl:when>
      <xsl:otherwise>&#160;</xsl:otherwise>
    </xsl:choose>
  </c>
  <c><xref target="{@anchor}"/></c>
</xsl:template>

</xsl:transform>