<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               xmlns:x="http://purl.org/net/xml2rfc/ext"
               xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'
               version="1.0"
               exclude-result-prefixes="rdf x"
>

<xsl:output indent="yes" omit-xml-declaration="yes"/>

<xsl:template match="/">
  <xsl:variable name="table">
    <texttable align="left" suppress-title="true" anchor="iana.header.registration.table">
      <ttcol>Header Field Name</ttcol>
      <ttcol>Protocol</ttcol>
      <ttcol>Status</ttcol>
      <ttcol>Reference</ttcol>
      <xsl:text>&#10;</xsl:text>
      <xsl:apply-templates select="//section[iref/@item='Headers']">
        <xsl:sort select="iref[@item='Headers']/@subitem"/>
      </xsl:apply-templates>
    </texttable>
    <xsl:text>&#10;</xsl:text>
  </xsl:variable>

  <xsl:comment>AUTOGENERATED FROM extract-header-defs.xslt, do not edit manually</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <xsl:copy-of select="$table"/>
  <xsl:comment>(END)</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  
    <!-- check against current version -->
  <xsl:variable name="oldtable" select="//texttable[@anchor='iana.header.registration.table']" />

  <xsl:if test="string($table//ttcol | $table//c) != string($oldtable//ttcol | $oldtable//c)">
    <xsl:message>WARNING: table contained inside source document needs to be updated!</xsl:message>
  </xsl:if>

</xsl:template>

<xsl:template match="section">
  <xsl:text>&#10;</xsl:text>
  <c><xsl:value-of select="iref[@item='Headers']/@subitem"/></c>
  <c>http</c>
  <c>
    <xsl:choose>
      <xsl:when test="ancestor::middle">standard</xsl:when>
      <xsl:otherwise>&#160;</xsl:otherwise>
    </xsl:choose>
  </c>
  <c><xref target="{@anchor}"/></c>
</xsl:template>

</xsl:transform>