/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `hcreate' function. */
#define HAVE_HCREATE 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "bap"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "bap 1.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "bap"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2"
